# 生產環境使用的 docker
FROM node:20-slim AS builder

WORKDIR /app

COPY . .

RUN npm install --legacy-peer-deps
RUN npm run build

create nginx container
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]